### ISSUE TITLE
QgsFields object has no attribute iteritems

### ISSUE THREAD

**Issue by PedroVenancio** [yellow-sky/FieldPyculator#12]
Maybe a problem related with API changes for version 2.0?
http://hub.qgis.org/wiki/quantum-gis/API_changes_for_version_20 

An error has occured while executing Python code:
Traceback (most recent call last):
  File "/home/pedro/.qgis//python/plugins/fieldpyculator/fieldpyculatorplugin.py", line 79, in run
    dlg = FieldPyculatorDialog(self.iface)
  File "/home/pedro/.qgis//python/plugins/fieldpyculator/fieldpyculatordialog.py", line 47, in **init**
    self.ui.cmbUpdateField.addItems(self.GetFieldNames(self.active_layer))
  File "/home/pedro/.qgis//python/plugins/fieldpyculator/fieldpyculatordialog.py", line 347, in GetFieldNames
    for num, field in field_map.iteritems():
AttributeError: 'QgsFields' object has no attribute 'iteritems'

Python version:
2.7.3 (default, Aug  1 2012, 05:27:35) 
[GCC 4.6.3]

QGIS version:
1.9.0-Master Master, exported

**Comment by yellow-sky** [comment]
Realization in https://github.com/yellow-sky/RuGeocoder/commit/66a9c2613cb1b9b6428ddeb787ef480583cd95e2
